export enum Career {
  INGENIERIA_INDUSTRIAL = 'ingenieria-industrial',
  INGENIERIA_INFORMATICA = 'ingenieria-informatica',
  INGENIERIA_CIVIL = 'ingenieria-civil',
  INGENIERIA_TELECOMUNICACIONES = 'ingenieria-telecomunicaciones',
  ARQUITECTURA = 'arquitectura',
  DERECHO = 'derecho',
  PSICOLOGIA = 'psicologia',
  FILOSOFIA = 'filosofia',
  TEOLOGIA = 'teologia',
  LETRAS = 'letras',
  EDUCACION = 'educacion',
  COMUNICACION_SOCIAL = 'comunicacion-social',
  ADMINISTRACION = 'administracion',
  CONTADURIA = 'contaduria',
  RELACIONES_INDUSTRIALES = 'relaciones-industriales',
  SOCIOLOGIA = 'sociologia',
  ECONOMIA = 'economia',
}
