name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NESTJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /var/www 
            if [ ! -d "LRT-prod-backend" ]; then
              mkdir LRT-prod-backend
              cd LRT-prod-backend
              git clone git@github.com:HopeAero/LRT-Backend.git
              cd LRT-Backend
              git pull
              npm install
              npm run build
              pm2 restart ucab-main-profile
              pm2 save    
              echo 'Repository cloned successfully to digital ocean'
            else
              cd LRT-prod-backend
              cd LRT-Backend
              git pull
              npm install
              npm run build
              pm2 restart ucab-main-profile
              pm2 save
              echo 'Repository already exists previously, pulling changes'
            fi
